### ISSUE TITLE
Abstract.sortObject() ignores number value 0

### ISSUE THREAD

**Issue by jkondratowicz** [paymentwall/paymentwall-node#20]
In `Abstract.sortObject()` method used for signature calculation, if parameter has a numeric value of 0 (happens for me for for pingback type=0), it's improperly cast to "" instead of "0", thus failing the validation of signature. I'd make a PR, but not sure how exactly you want to treat this issue - what's the policy regarding undefined or null values passed. ~For now I'll use a workaround and manually cast each pingback parameter to String.~ OK, I see the issue - type is manually cast to Int in `getType()` method, so if I use this method before validating signature, it breaks it...

Another issue is that `Pingback.getPingbackUniqueId()` gets `undefined` for the second bit, but I haven't looked into that (if it's related to sortObject implementation). So for example pingback with params `type=0&ref=ABC123XYZ`, `getPingbackUniqueId()` returns `ABC123XYZ_undefined`.

**Comment by jkondratowicz** [comment]
OK, so after some digging I know the reason it is like this - if I call `pingback.getType()` before validating it, later validation will fail. Quick fix is to save local copy of `type` parameter in `Pingback.getType()` method and cast it to Int, not the original param from `this.parameters['type']`.

**Comment by hdolinski** [comment]
Hi Jan,

fixed this in 1.2.4, please run npm update to get the latest version
