### ISSUE TITLE
Pingback error

### ISSUE THREAD

**Issue by matyas-igor** [paymentwall/paymentwall-node#3]
pingback.js getType 120
```javascript
  if (this.parameters['type']) { ... }
```
When I have successful callback with type = 0 it fails on this string

It has to have another checking only for undefined, like this 

```javascript
  if (typeof this.parameters['type'] != 'undefined') { ... }
```

**Comment by davex69** [comment]
Thank you for contributing! It was fixed in https://github.com/paymentwall/paymentwall-node/pull/5
