### ISSUE TITLE
Paingback types

### ISSUE THREAD

**Issue by matyas-igor** [paymentwall/paymentwall-node#4]
According to this documentation https://www.paymentwall.com/en/documentation/Digital-Goods-API/710#pingback_processing will you support all the callback types? 12, 13, 14, 200, 201, 202?

**Comment by liufanhhh** [comment]
Hi,

Currently we don't support the types you mentioned but we have a plan and we will support all pingback types soon.

**Comment by liufanhhh** [comment]
Currently you can get the type value in pingback validate function like this:
 

```javascript
// used express
var ip = req.headers['x-forwarded-for'] ||
             req.connection.remoteAddress ||
             req.socket.remoteAddress ||
             req.connection.socket.remoteAddress;

var pingback = new Paymentwall.Pingback(req.query, ip);
if (pingback.validate()) {
  var type = req.query.type;
  console.log('OK'); // Paymentwall expects the string OK in response, otherwise the pingback will be resent
} else {
  console.log(pingback.getErrorSummary());
}
```
