### ISSUE TITLE
Brick support

### ISSUE THREAD

**Issue by despotix** [paymentwall/paymentwall-node#6]
Does this lib supports brick method?
https://github.com/paymentwall/paymentwall-php#brick

**Comment by kristianladd** [comment]
It does, you can create charges in the following way :
https://github.com/paymentwall/paymentwall-php/blob/master/README.md#charge

**Comment by despotix** [comment]
Сan you please provide node.js code sample, for clarity?

**Comment by kristianladd** [comment]
Hi

Paymentwall Node.js library currently does not yet have wrappers for Brick
API, but the API is very lightweight and you can do a charge from your
backend easily.
You can find an example of how to send a charge request via curl following
the link below:
https://www.paymentwall.com/en/documentation/Brick/2968#create-a-charge

Thanks
Ivan

On Mon, Jul 13, 2015 at 11:48 PM, despotix <notifications@github.com> wrote:

> Сan you please provide node.js code sample, for clarity?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paymentwall/paymentwall-node/issues/6#issuecomment-120975063>
> .
>



-- 

*IVAN KOVALYOV*
Product Manager - Brick
vanya@paymentwall.com
skype: ivan.kovalyov
gtalk: vanya@paymentwall.com

*Paymentwall Inc.*
www.paymentwall.com
Let's meet!  [image: White Nights]
<https://www.paymentwall.com/en/events/white-nights-2015-russia?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=wn15>
White
Nights Conference
<https://www.paymentwall.com/en/events/white-nights-2015-russia?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=wn15>
St. Petersburg
  [image: E3 2015]
<https://www.paymentwall.com/en/events/chinajoy-2015?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=e3>
ChinaJoy
2015
<https://www.paymentwall.com/en/events/chinajoy-2015?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=e3>
Shanghai
  [image: Europas awards 2015]
<https://www.paymentwall.com/en/events/gdc-europe-2015?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh>
GDC Europe
<https://www.paymentwall.com/en/events/gdc-europe-2015?utm_source=email_footer&utm_term=293&utm_campaign=050515>
Cologne
   <https://www.paymentwall.com/?utm_source=email>

San Francisco - Las Vegas - Amsterdam - Berlin - Istanbul - Kiev - Beijing
- Manila - Hanoi - São Paulo

**Comment by ivan-kovalyov** [comment]
Hi

Paymentwall Node.js library currently does not yet have wrappers for Brick
API, but the API is very lightweight and you can do a charge from your
backend easily.
You can find an example of how to send a charge request via curl following
the link below:
https://www.paymentwall.com/en/documentation/Brick/2968#create-a-charge

Thanks
Ivan

**Comment by despotix** [comment]
I'm doing like in link you have provided, but have an `undefined` response instead of getting correct response like in documentation or error response. Please see my request and response below.

Request
<pre>
{
  amount: '11',
  currency: 'USD',
  description: 'Charge for ***tix@gmail.com',
  email: '***tix@gmail.com',
  fingerprint: '*****vdIY6C7PvvQXep9IVmgmiAYYMvm',
  token: 'ot_a45e1d3288c05a265310729bbbe*****' 
}
</pre>
Response
<pre>
Error   : null
Result : undefined
</pre>

The same situation with using `curl`
![image](https://cloud.githubusercontent.com/assets/4264214/8796589/7ff16cfe-2f9e-11e5-9131-b2524bd7b7ab.png)

Am I doing something wrong?

**Comment by hdolinski** [comment]
Current version now supports Brick API
